#! /usr/bin/env python3
##  linkall - creates links to all files in a directory
##  Copyright (C) 2015 David McMackins II
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Affero General Public License as published by
##  the Free Software Foundation, version 3 only.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU Affero General Public License for more details.
##
##  You should have received a copy of the GNU Affero General Public License
##  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

from sys import argv
from os import symlink, listdir
from os.path import realpath
from getopt import gnu_getopt

target_dir = "./"

opts, args = gnu_getopt(argv[1:], "t:", ["target="])

for key, value in opts:
    if key in ("-t", "--target"):
        target_dir = value
    else:
        print("linkall: Unrecognized option: %s" %key)
        exit(1)

target_dir = realpath(target_dir) + '/'

for arg in args:
    for f in listdir(realpath(arg)):
        symlink(realpath(f), target_dir + f)
